server:
  port: 8092

spring:
  application:
    name: external-api
  main:
    web-application-type: servlet

management:
  server:
    port: 8093

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
