# OpenFrame Authorization Server Configuration
# Server Configuration
spring:
  main:
    web-application-type: servlet
  port: 9000

  # Spring Cloud Config
  cloud:
    config:
      enabled: false

# CORS Configuration
cors:
  allowed-origins:
    - "http://localhost:*"
    - "https://localhost:*"
    - "http://localhost"
    - "https://localhost"
    - "http://localhost:3000"
    - "https://localhost:3000"
    - "http://localhost:5173"
    - "https://localhost:5173"
  allowed-methods: [ GET, POST, PUT, DELETE, OPTIONS ]
  allowed-headers: [ "*" ]
  allow-credentials: true
  max-age: 3600

# OpenFrame Configuration
openframe:
  auth:
    # Gateway OAuth2 Client Configuration
    gateway:
      client:
        id: openframe-gateway
        secret: openframe-gateway-secret
      redirect-uri: https://localhost/oauth/callback
  tenants:
    default-tenant: localhost
    default-domain: localhost

  # Domain validation regex (only localhost for local development)
  domain:
    validation:
      regex: "^localhost$"

  # OAuth2 Token Configuration
  security:
    jwt:
      access-token-expiration: 900    # 15 minutes
      refresh-token-expiration: 604800 # 7 days

  # SSO Configuration
  sso:
    google:
      authorization-url: https://accounts.google.com/o/oauth2/v2/auth
      token-url: https://oauth2.googleapis.com/token
      user-info-url: https://www.googleapis.com/oauth2/v2/userinfo
      redirect-uri: https://localhost/oauth2/callback/google
      scopes: openid,profile,email
      enabled: true
      display-name: Google

# Security OAuth2 Token Configuration (for CookieService)
security:
  encryption:
    password: ${ENCRYPTION_PASSWORD:kdCJxik7VWRlG5L8jKHBeJQK5unssi7u1uHOd01b75ilr8n}
    salt: ${ENCRYPTION_SALT:74f62c51327175b05abe1ad78030565c}

# Logging Configuration
logging:
  level:
    com.openframe: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization.web.OAuth2TokenEndpointFilter: TRACE
    org.springframework.security.oauth2.server.authorization.authentication.OAuth2AuthorizationCodeAuthenticationProvider: TRACE
    org.springframework.security.oauth2.server.authorization: TRACE

# Management server configuration
management:
  server:
    port: 9001
