# API service docker environment configuration
spring:
  kafka:
    bootstrap-servers: kafka.datasources.svc.cluster.local:9092

oauth:
  client:
    default:
      id: openframe_web_dashboard
      secret: prod_secret

fleet:
  api:
    url: http://fleet.integrated-tools.svc.cluster.local:8070

openframe:
  management:
    url: http://openframe-management.microservices.svc.cluster.local:8095
    key: ${OPENFRAME_MANAGEMENT_KEY:docker-management-key-123}

security:
  encryption:
    password: ${ENCRYPTION_PASSWORD:kdCJxik7VWRlG5L8jKHBeJQK5unssi7u1uHOd01b75ilr8n}
    salt: ${ENCRYPTION_SALT:74f62c51327175b05abe1ad78030565c}
      
