spring:
  kafka:
    bootstrap-servers: kafka.datasources.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

oauth:
  client:
    default:
      id: openframe_client
      secret: prod_secret

openframe:
  management:
    url: http://openframe-management.microservices.svc.cluster.local:8095
    key: ${OPENFRAME_MANAGEMENT_KEY:docker-management-key-123}